version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_DB=mycv
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/postgresql:/var/lib/postgresql
      - ~/postgresql/data:/var/lib/postgresql/data
  
  app:
    build: .
    environment:
      - MYCV_DATASOURCE=jdbc:postgresql://postgres:5432/mycv
      - MYCV_DB_USERNAME=postgres
      - MYCV_DB_PASSWORD=postgres
      - JWT_SECRET=wHqRTjE8tXtgm/zhvn1qmmxLkcA+MvjnbX0aLkNhLm4=
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - MAILGUN_SMTP_PASSWORD=${MAILGUN_SMTP_PASSWORD}
      - MAILGUN_SMTP_USERNAME=${MAILGUN_SMTP_USERNAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

