alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: mycvhub.ch
  type: PRIMARY
  zone: mycvhub.ch
envs:
- key: MYCV_DATASOURCE
  scope: RUN_AND_BUILD_TIME
  value: ${{ secrets.DO_DB_URL }}
- key: MYCV_DB_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: ${{ secrets.DO_DB_USERNAME }}
- key: SPRING_PROFILES_ACTIVE
  scope: RUN_AND_BUILD_TIME
  value: prod
- key: MYCV_DB_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ${{ secrets.DO_DB_PASSWORD }}
- key: JWT_ACCESS_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ${{ secrets.DO_JWT_SECRET }}
- key: JWT_REFRESH_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ${{ secrets.DO_JWT_REFRESH_SECRET }}
- key: CLOUDINARY_API_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ${{ secrets.DO_CLOUDINARY_KEY }}
- key: CLOUDINARY_API_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ${{ secrets.DO_CLOUDINARY_SECRET }}
- key: CLOUDINARY_CLOUD_NAME
  scope: RUN_AND_BUILD_TIME
  value: ${{ secrets.DO_CLOUDINARY_NAME }}
- key: MAILGUN_SMTP_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: ${{ secrets.DO_MAIL_SMTP_USERNAME }}
- key: MAILGUN_SMTP_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ${{ secrets.DO_MAIL_SMTP_PASSWORD }}
- key: GITHUB_CLIENT_ID
  scope: RUN_AND_BUILD_TIME
  value: ${{ secrets.DO_GITHUB_CLIENT_ID }}
- key: GITHUB_CLIENT_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ${{ secrets.DO_GITHUB_CLIENT_SECRET }}
- key: ADMIN_SEED_USERNAME
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ${{ secrets.DO_ADMIN_SEED_USERNAME }}
- key: ADMIN_BOOTSTRAP_TEMPORARY_PASSWORD_EXPIRATION_MINUTES
  scope: RUN_AND_BUILD_TIME
  value: "30"
- key: ADMIN_LOGIN_RATE_LIMIT_MAX_FAILED_ATTEMPTS
  scope: RUN_AND_BUILD_TIME
  value: "5"
- key: ADMIN_LOGIN_RATE_LIMIT_LOCKOUT_MINUTES
  scope: RUN_AND_BUILD_TIME
  value: "15"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: my-cv
    match:
      path:
        prefix: /
name: my-cv-app
region: fra
services:
- http_port: 8080
  health_check:
    initial_delay_seconds: 120
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 12
    http_path: /actuator/health/readiness
    port: 8080
  image:
    registry: lstreckeisen
    registry_credentials: ${{ secrets.DO_DOCKER_REGISTRY_CREDENTIALS }}
    registry_type: DOCKER_HUB
    repository: my-cv
    tag: ${{ github.sha }}
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  liveness_health_check:
    initial_delay_seconds: 180
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 12
    http_path: /actuator/health/liveness
    port: 8080
  log_destinations:
  - logtail:
      token: ${{ secrets.DO_LOGTAIL_TOKEN }}
    name: Better Stack
  name: my-cv
  termination:
    drain_seconds: 30
    grace_period_seconds: 90
