spring.datasource:
  url: jdbc:postgresql://localhost:5432/mycv
  username: postgres
  password: postgres

logging:
  file.name: ./logs/mycv.log

my-cv:
  security:
    jwt:
      secret: wHqRTjE8tXtgm/zhvn1qmmxLkcA+MvjnbX0aLkNhLm4=
  frontend:
    base-url: http://localhost:3000/ui