spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mycv
    username: postgres
    password: postgres
  security.oauth2.client.registration.github.redirect-uri: "{baseUrl}/api/auth/oauth2/callback/github"

logging:
  file.name: ./logs/mycv.log

my-cv:
  security:
    jwt:
      secret: wHqRTjE8tXtgm/zhvn1qmmxLkcA+MvjnbX0aLkNhLm4=
  frontend:
    base-url: http://localhost:3000/ui